// <auto-generated />

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Persona")]
[assembly: Guid("282f66cb-9792-42a5-8d06-a6cb104fcdeb")]
[assembly: CLSCompliant(true)]
