// <auto-generated />
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant", Justification = "Not reasonable for ASP.NET applications.")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "PersonaExample.MvcApplication.#Application_Start()", Justification = "Required by ASP.NET.")]
