// <auto-generated />
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant", Justification = "Not reasonable for ASP.NET applications.")]
[assembly: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "PersonaExample.Controllers.AuthController.#Index(System.String)", Justification = "This comes in via the query string.")]
